### ISSUE TITLE
Trello analysis

### ISSUE THREAD

**Issue by Mikanebu** [datopian/ourbot#71] opened 2017-09-08 11:10 UTC
We want to have an analysis on automating Trello functionality in our bot.

## Acceptance criteria

* [ ] Analysis on Trello functionality

## Tasks

* [ ] Write analysis on Trello functionality 
  * [ ] Possible command we can create such as `creating tasks, move tasks to appropriate statuses, show lists`
    * [ ] check this package [hubot-trello](https://github.com/hubot-scripts/hubot-trello)

## Analysis 

Interesting packages for trello functionality
https://github.com/hubot-scripts/hubot-trello

**Comment by rufuspollock** [comment] 2018-05-06 13:49
DUPLICATE of #23.

**Closed as completed by rufuspollock** 2018-05-06 13:49 UTC
